### ISSUE TITLE
bodhibuilder creates duplicate sources entry

### ISSUE THREAD

**Issue by JeffHoogland** [stacefauske/bodhibuilder#2]
When remastering a system that has been remastered. Details: http://forums.bodhilinux.com/index.php?/topic/14092-bodhibuilder-adds-duplicate-entry-to-sourceslist/

**Comment by stacefauske** [comment]
This issue is still present in 2.1.x versions for now, but has been fixed in 2.2.x versions for *buntu 16.04. 

I'll close the issue when I also port the fix to 2.1.x.

**Comment by stacefauske** [comment]
Added fix to git repo. Still need to create deb and put on sourceforge.

**Comment by stacefauske** [comment]
Issue was fixed
