### ISSUE TITLE
need help with bodhibuilder after complete not letting me log in

### ISSUE THREAD

**Issue by tjw0lf** [stacefauske/bodhibuilder#3]
I used bodhibuilder and after its complete and everything ans the ISO is made i test in virtaulbox and i can not log in it keeps saying incorrect password .I made a respin of Linux lite

**Comment by stacefauske** [comment]
It should create a live user without a password under most circumstances.
If you didn't change the /etc/bodhibuilder.conf file, please try the username bodhi with no password. If you changed the liveuser name in the config file above, try entering the live user name with no password.

**Comment by tjw0lf** [comment]
No i didn't change anything anywhere was i supposed to. I thought i did try bodhi but still didn't work. I just clicked the dist option that was the correct one right. I will try again

**Comment by tjw0lf** [comment]
I don't even see a bodhibuilder.conf file in there. Just bodhibuilder.version. So maybe i did it wrong idk. I hit the dist butten. I'm i supposed to hit something else before that

**Comment by stacefauske** [comment]
If the install went right these should exist:
/etc/bodhibuilder/    (a directory)
/etc/bodhibuilder.conf    (a config file)

If you didn't change the config file try username bodhi. If the config file doesn't exist please try uninstalling then reinstalling bodhibuilder.

**Comment by tjw0lf** [comment]
I reinstalled bodhibuilder 2.2.4.all.deb
i got the /etc/bodhibuilder/ (a directory)
but not this /etc/bodhibuilder.conf (a config file)

**Comment by stacefauske** [comment]
It appears as though bodhibuilder isn't installing correctly on your system. Is Linux Lite an Ubuntu based OS? And if so, which Ubuntu is it based off of?

Alternatively you could try creating the file /etc/bodhibuilder.conf and put in the contents of that file in my repo here.

For curiosity sake, can you attach your log file?   /home/bodhibuilder/bodhibuilder/bodhibuilder.log

**Comment by tjw0lf** [comment]
OK i found why. I was using virtualbox and some how it doesn't like it. why is that. using it on my real hardware is fine
