### ISSUE TITLE
How can i edit with this need to add links in desktop

### ISSUE THREAD

**Issue by tjw0lf** [stacefauske/bodhibuilder#4]
i need to edit the files. to add links to desktop for my respin. How can i do this. also need to change .face in the folder. I found the spot to change its the dummysys folder right. I added the links in to etc/skel/Desktop/ But how do i update it and remake the iso. If you can help that would be great Thank you

**Comment by stacefauske** [comment]
To add files to the desktop, you can edit the directories '/home/bodhibuilder/bodhibuilder/dummysys/etc/skel/' or your own skel directory at '/etc/skel/'. If you have a Desktop directory in there.

What does this mean?  "also need to change .face in the folder."

If you do a 'Distcdfs' in the GUI or 'sudo bodhibuilder -d cdfs' in the terminal, when it is done working you can edit the files in '/home/bodhibuilder/bodhibuilder/dummysys/' or '/home/bodhibuilder/bodhibuilder/ISOTMP/' to customize your ISO. Then when you have made your edits, do either 'Distiso' in the GUI or 'sudo bodhibuilder -d iso (isoname.iso)' in the terminal to finish the creation of your ISO.

Hope that helps a little. You kind of have to play around with it a bit to get things just the way you like them.

**Comment by stacefauske** [comment]
Closing issue due to no followup.
